[package]
name = "vision"
version = "0.1.0"
edition = "2021"

[[bin]]
name="vision_node"
path="src/main.rs"

[dependencies]
rclrs = "*"
anyhow = "*"
sensor_msgs = "*"
std_msgs = "*"
messages = "*"

[dependencies.opencv]
version = "0.95"
features = ["clang-runtime"]
