[develop]
script_dir=$base/lib/vision_py

[install]
install_scripts=$base/lib/vision_py

[options.entry_points]
console_scripts =
    vision_node = scripts.vision_node:main
    dvs_raw_serial_node = scripts.dvs_raw_serial_node:main
    dvs_minimal_record_node = scripts.dvs_minimal_record_node:main
    dvs_avoid_key_node = scripts.dvs_avoid_key_node:main
    